In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data=pd.read_csv('insurance.csv')
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 57.5+ KB

In [7]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()
cats=data.select_dtypes(include=['object'])
cats

         sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
5     female     no  southeast
6     female     no  southeast
7     female     no  northwest
8       male     no  northeast
9     female     no  northwest
10      male     no  northeast
11    female    yes  southeast
12      male     no  southwest
13    female     no  southeast
14      male    yes  southeast
15      male     no  southwest
16    female     no  northeast
17      male     no  northeast
18      male     no  southwest
19      male    yes  southwest
20    female     no  northeast
21    female     no  southwest
22      male     no  southeast
23    female    yes  northeast
24      male     no  northwest
25    female     no  southeast
26    female     no  northeast
27    female     no  northwest
28      male     no  northwest
29      male    yes  southwest
...      ...    ...        ...
1308  female    yes  southwest
1309    male     no  southwest
1310    male     no  northwest
1311  female     no  northwest
1312    male     no  southwest
1313  female    yes  southwest
1314  female    yes  northwest
1315    male     no  northeast
1316  female     no  southwest
1317    male     no  southeast
1318    male     no  northeast
1319  female     no  northwest
1320    male     no  northwest
1321    male    yes  northeast
1322    male     no  southeast
1323  female    yes  southeast
1324    male     no  northwest
1325    male     no  northeast
1326  female     no  northeast
1327    male     no  southeast
1328  female     no  northeast
1329    male     no  southwest
1330  female     no  southeast
1331  female     no  southwest
1332  female     no  southwest
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1338 rows x 3 columns]

In [9]:
cats_conv=ohe.fit_transform(cats).toarray()
cats_conv

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [10]:
cats_encoded=pd.DataFrame(cats_conv)
cats_encoded

        0    1    2    3    4    5    6    7
0     1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
1     0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
2     0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
3     0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
4     0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
5     1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
6     1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
7     1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
8     0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
9     1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
10    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
11    1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
12    0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
13    1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
14    0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
15    0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
16    1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
17    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
18    0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
19    0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
20    1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
21    1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
22    0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
23    1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0
24    0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
25    1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
26    1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
27    1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
28    0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
29    0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
...   ...  ...  ...  ...  ...  ...  ...  ...
1308  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
1309  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
1310  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
1311  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
1312  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
1313  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
1314  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
1315  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
1316  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
1317  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
1318  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
1319  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
1320  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
1321  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0
1322  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
1323  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
1324  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
1325  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0
1326  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
1327  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
1328  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
1329  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
1330  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
1331  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
1332  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
1333  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
1334  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
1335  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
1336  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
1337  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0

[1338 rows x 8 columns]

In [11]:
data.drop(columns=data.columns,inplace=True)

In [12]:
new_data=pd.concat([cats_encoded,data],ignore_index=True,axis=1)

In [13]:
X=new_data.iloc[:,:-1]
y=new_data.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=50)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
lr.coef_

array([-5.55258736e-17,  4.46691295e-17,  1.29995840e-16,  1.05899447e-16,
       -1.00000000e+00, -1.00000000e+00, -1.00000000e+00])

In [16]:
from sklearn.metrics import r2_score, mean_squared_error

y_pred=lr.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

1.0
1.036207800526434e-31